/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutputXlinkValid model module.
 * @module qan/qan/OutputXlinkValid
 * @version 0.0.2
 */
class OutputXlinkValid {
    /**
     * Constructs a new <code>OutputXlinkValid</code>.
     * @alias module:qan/qan/OutputXlinkValid
     * @param validity {String} The xlink validity time of the specified address.
     */
    constructor(validity) { 
        
        OutputXlinkValid.initialize(this, validity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, validity) { 
        obj['Validity'] = validity;
    }

    /**
     * Constructs a <code>OutputXlinkValid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:qan/qan/OutputXlinkValid} obj Optional instance to populate.
     * @return {module:qan/qan/OutputXlinkValid} The populated <code>OutputXlinkValid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutputXlinkValid();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('Validity')) {
                obj['Validity'] = ApiClient.convertToType(data['Validity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutputXlinkValid</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutputXlinkValid</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OutputXlinkValid.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['$schema'] && !(typeof data['$schema'] === 'string' || data['$schema'] instanceof String)) {
            throw new Error("Expected the field `$schema` to be a primitive type in the JSON string but got " + data['$schema']);
        }
        // ensure the json data is a string
        if (data['Validity'] && !(typeof data['Validity'] === 'string' || data['Validity'] instanceof String)) {
            throw new Error("Expected the field `Validity` to be a primitive type in the JSON string but got " + data['Validity']);
        }

        return true;
    }


}

OutputXlinkValid.RequiredProperties = ["Validity"];

/**
 * A URL to the JSON Schema for this object.
 * @member {String} $schema
 */
OutputXlinkValid.prototype['$schema'] = undefined;

/**
 * The xlink validity time of the specified address.
 * @member {String} Validity
 */
OutputXlinkValid.prototype['Validity'] = undefined;






export default OutputXlinkValid;

