/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorModel from '../qan/ErrorModel';
import InputCall from '../qan/InputCall';
import InputEstimateGas from '../qan/InputEstimateGas';
import InputFeeHistory from '../qan/InputFeeHistory';
import InputGetLogs from '../qan/InputGetLogs';
import InputGetProof from '../qan/InputGetProof';
import InputGetStorageAt from '../qan/InputGetStorageAt';
import InputNewFilter from '../qan/InputNewFilter';
import InputSendRawTransaction from '../qan/InputSendRawTransaction';
import OutputBlockNumber from '../qan/OutputBlockNumber';
import OutputCall from '../qan/OutputCall';
import OutputChainId from '../qan/OutputChainId';
import OutputEstimateGas from '../qan/OutputEstimateGas';
import OutputFeeHistory from '../qan/OutputFeeHistory';
import OutputGasPrice from '../qan/OutputGasPrice';
import OutputGetBalance from '../qan/OutputGetBalance';
import OutputGetBlockByHash from '../qan/OutputGetBlockByHash';
import OutputGetBlockByNumber from '../qan/OutputGetBlockByNumber';
import OutputGetBlockReceipts from '../qan/OutputGetBlockReceipts';
import OutputGetBlockTransactionCountByHash from '../qan/OutputGetBlockTransactionCountByHash';
import OutputGetBlockTransactionCountByNumber from '../qan/OutputGetBlockTransactionCountByNumber';
import OutputGetCode from '../qan/OutputGetCode';
import OutputGetFilterChanges from '../qan/OutputGetFilterChanges';
import OutputGetFilterLogs from '../qan/OutputGetFilterLogs';
import OutputGetLogs from '../qan/OutputGetLogs';
import OutputGetProof from '../qan/OutputGetProof';
import OutputGetStorageAt from '../qan/OutputGetStorageAt';
import OutputGetTransactionByBlockHashAndIndex from '../qan/OutputGetTransactionByBlockHashAndIndex';
import OutputGetTransactionByBlockNumberAndIndex from '../qan/OutputGetTransactionByBlockNumberAndIndex';
import OutputGetTransactionByHash from '../qan/OutputGetTransactionByHash';
import OutputGetTransactionCount from '../qan/OutputGetTransactionCount';
import OutputGetTransactionReceipt from '../qan/OutputGetTransactionReceipt';
import OutputMaxPriorityFeePerGas from '../qan/OutputMaxPriorityFeePerGas';
import OutputNewBlockFilter from '../qan/OutputNewBlockFilter';
import OutputNewFilter from '../qan/OutputNewFilter';
import OutputNewPendingTransactionFilter from '../qan/OutputNewPendingTransactionFilter';
import OutputSendRawTransaction from '../qan/OutputSendRawTransaction';
import OutputSyncing from '../qan/OutputSyncing';
import OutputUninstallFilter from '../qan/OutputUninstallFilter';
import OutputXlinkValid from '../qan/OutputXlinkValid';

/**
* QAN service.
* @module qan/api/QANApi
* @version 0.0.2
*/
export default class QANApi {

    /**
    * Constructs a new QANApi. 
    * @alias module:qan/api/QANApi
    * @class
    * @param {module:qan/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:qan/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the qanBlockNumber operation.
     * @callback module:qan/api/QANApi~qanBlockNumberCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputBlockNumber} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the latest block number of the blockchain.
     * @param {module:qan/api/QANApi~qanBlockNumberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputBlockNumber}
     */
    qanBlockNumber(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputBlockNumber;
      return this.apiClient.callApi(
        '/blockNumber/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanCall operation.
     * @callback module:qan/api/QANApi~qanCallCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputCall} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Executes a new message call immediately without creating a transaction on the block chain.
     * @param {module:qan/qan/InputCall} inputCall 
     * @param {module:qan/api/QANApi~qanCallCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputCall}
     */
    qanCall(inputCall, callback) {
      let postBody = inputCall;
      // verify the required parameter 'inputCall' is set
      if (inputCall === undefined || inputCall === null) {
        throw new Error("Missing the required parameter 'inputCall' when calling qanCall");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputCall;
      return this.apiClient.callApi(
        '/call/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanChainId operation.
     * @callback module:qan/api/QANApi~qanChainIdCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputChainId} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the current network/chain ID, used to sign replay-protected transaction introduced in EIP-155.
     * @param {module:qan/api/QANApi~qanChainIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputChainId}
     */
    qanChainId(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputChainId;
      return this.apiClient.callApi(
        '/chainId/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanEstimateGas operation.
     * @callback module:qan/api/QANApi~qanEstimateGasCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputEstimateGas} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an estimation of gas for a given transaction.
     * @param {module:qan/qan/InputEstimateGas} inputEstimateGas 
     * @param {module:qan/api/QANApi~qanEstimateGasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputEstimateGas}
     */
    qanEstimateGas(inputEstimateGas, callback) {
      let postBody = inputEstimateGas;
      // verify the required parameter 'inputEstimateGas' is set
      if (inputEstimateGas === undefined || inputEstimateGas === null) {
        throw new Error("Missing the required parameter 'inputEstimateGas' when calling qanEstimateGas");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputEstimateGas;
      return this.apiClient.callApi(
        '/estimateGas/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanFeeHistory operation.
     * @callback module:qan/api/QANApi~qanFeeHistoryCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputFeeHistory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the collection of historical gas information.
     * @param {module:qan/qan/InputFeeHistory} inputFeeHistory 
     * @param {module:qan/api/QANApi~qanFeeHistoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputFeeHistory}
     */
    qanFeeHistory(inputFeeHistory, callback) {
      let postBody = inputFeeHistory;
      // verify the required parameter 'inputFeeHistory' is set
      if (inputFeeHistory === undefined || inputFeeHistory === null) {
        throw new Error("Missing the required parameter 'inputFeeHistory' when calling qanFeeHistory");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputFeeHistory;
      return this.apiClient.callApi(
        '/feeHistory/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGasPrice operation.
     * @callback module:qan/api/QANApi~qanGasPriceCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGasPrice} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the current gas price on the network in wei.
     * @param {module:qan/api/QANApi~qanGasPriceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGasPrice}
     */
    qanGasPrice(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGasPrice;
      return this.apiClient.callApi(
        '/gasPrice/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBalance operation.
     * @callback module:qan/api/QANApi~qanGetBalanceCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBalance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the balance of the account of given address.
     * @param {String} address A 20 bytes long hexadecimal value representing an address
     * @param {Object} opts Optional parameters
     * @param {String} [blockNumber = 'latest')] The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {module:qan/api/QANApi~qanGetBalanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBalance}
     */
    qanGetBalance(address, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'address' is set
      if (address === undefined || address === null) {
        throw new Error("Missing the required parameter 'address' when calling qanGetBalance");
      }

      let pathParams = {
        'Address': address
      };
      let queryParams = {
        'BlockNumber': opts['blockNumber']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBalance;
      return this.apiClient.callApi(
        '/getBalance/{Address}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBlockByHash operation.
     * @callback module:qan/api/QANApi~qanGetBlockByHashCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBlockByHash} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns information of the block matching the given block hash.
     * @param {String} hash The hash (32 bytes) of the block
     * @param {Boolean} transactionDetailFlag The method returns the full transaction objects when this value is true otherwise, it returns only the hashes of the transactions
     * @param {module:qan/api/QANApi~qanGetBlockByHashCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBlockByHash}
     */
    qanGetBlockByHash(hash, transactionDetailFlag, callback) {
      let postBody = null;
      // verify the required parameter 'hash' is set
      if (hash === undefined || hash === null) {
        throw new Error("Missing the required parameter 'hash' when calling qanGetBlockByHash");
      }
      // verify the required parameter 'transactionDetailFlag' is set
      if (transactionDetailFlag === undefined || transactionDetailFlag === null) {
        throw new Error("Missing the required parameter 'transactionDetailFlag' when calling qanGetBlockByHash");
      }

      let pathParams = {
        'Hash': hash,
        'TransactionDetailFlag': transactionDetailFlag
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBlockByHash;
      return this.apiClient.callApi(
        '/getBlockByHash/{Hash}/{TransactionDetailFlag}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBlockByNumber operation.
     * @callback module:qan/api/QANApi~qanGetBlockByNumberCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBlockByNumber} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns information of the block matching the given block number.
     * @param {String} blockNumber The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {Boolean} transactionDetailFlag The method returns the full transaction objects when this value is true otherwise, it returns only the hashes of the transactions
     * @param {module:qan/api/QANApi~qanGetBlockByNumberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBlockByNumber}
     */
    qanGetBlockByNumber(blockNumber, transactionDetailFlag, callback) {
      let postBody = null;
      // verify the required parameter 'blockNumber' is set
      if (blockNumber === undefined || blockNumber === null) {
        throw new Error("Missing the required parameter 'blockNumber' when calling qanGetBlockByNumber");
      }
      // verify the required parameter 'transactionDetailFlag' is set
      if (transactionDetailFlag === undefined || transactionDetailFlag === null) {
        throw new Error("Missing the required parameter 'transactionDetailFlag' when calling qanGetBlockByNumber");
      }

      let pathParams = {
        'BlockNumber': blockNumber,
        'TransactionDetailFlag': transactionDetailFlag
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBlockByNumber;
      return this.apiClient.callApi(
        '/getBlockByNumber/{BlockNumber}/{TransactionDetailFlag}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBlockReceipts operation.
     * @callback module:qan/api/QANApi~qanGetBlockReceiptsCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBlockReceipts} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns all transaction receipts for a given block.
     * @param {String} blockNumber The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {module:qan/api/QANApi~qanGetBlockReceiptsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBlockReceipts}
     */
    qanGetBlockReceipts(blockNumber, callback) {
      let postBody = null;
      // verify the required parameter 'blockNumber' is set
      if (blockNumber === undefined || blockNumber === null) {
        throw new Error("Missing the required parameter 'blockNumber' when calling qanGetBlockReceipts");
      }

      let pathParams = {
        'BlockNumber': blockNumber
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBlockReceipts;
      return this.apiClient.callApi(
        '/getBlockReceipts/{BlockNumber}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBlockTransactionCountByHash operation.
     * @callback module:qan/api/QANApi~qanGetBlockTransactionCountByHashCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBlockTransactionCountByHash} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the number of transactions for the block matching the given block hash.
     * @param {String} hash The hash of the block
     * @param {module:qan/api/QANApi~qanGetBlockTransactionCountByHashCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBlockTransactionCountByHash}
     */
    qanGetBlockTransactionCountByHash(hash, callback) {
      let postBody = null;
      // verify the required parameter 'hash' is set
      if (hash === undefined || hash === null) {
        throw new Error("Missing the required parameter 'hash' when calling qanGetBlockTransactionCountByHash");
      }

      let pathParams = {
        'Hash': hash
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBlockTransactionCountByHash;
      return this.apiClient.callApi(
        '/getBlockTransactionCountByHash/{Hash}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetBlockTransactionCountByNumber operation.
     * @callback module:qan/api/QANApi~qanGetBlockTransactionCountByNumberCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetBlockTransactionCountByNumber} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the number of transactions for the block matching the given block number.
     * @param {String} blockNumber The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {module:qan/api/QANApi~qanGetBlockTransactionCountByNumberCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetBlockTransactionCountByNumber}
     */
    qanGetBlockTransactionCountByNumber(blockNumber, callback) {
      let postBody = null;
      // verify the required parameter 'blockNumber' is set
      if (blockNumber === undefined || blockNumber === null) {
        throw new Error("Missing the required parameter 'blockNumber' when calling qanGetBlockTransactionCountByNumber");
      }

      let pathParams = {
        'BlockNumber': blockNumber
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetBlockTransactionCountByNumber;
      return this.apiClient.callApi(
        '/getBlockTransactionCountByNumber/{BlockNumber}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetCode operation.
     * @callback module:qan/api/QANApi~qanGetCodeCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetCode} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the compiled bytecode of a smart contract.
     * @param {String} address The address of the smart contract from which the bytecode will be obtained
     * @param {Object} opts Optional parameters
     * @param {String} [blockNumber = 'latest')] The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {module:qan/api/QANApi~qanGetCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetCode}
     */
    qanGetCode(address, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'address' is set
      if (address === undefined || address === null) {
        throw new Error("Missing the required parameter 'address' when calling qanGetCode");
      }

      let pathParams = {
        'Address': address
      };
      let queryParams = {
        'BlockNumber': opts['blockNumber']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetCode;
      return this.apiClient.callApi(
        '/getCode/{Address}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetFilterChanges operation.
     * @callback module:qan/api/QANApi~qanGetFilterChangesCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetFilterChanges} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Polling method for a filter, which returns an array of events that have occurred since the last poll.
     * @param {String} filterId The filter id that is returned from getFilterChangesnewFilter, getFilterChangesnewBlockFilter or getFilterChangesnewPendingTransactionFilter
     * @param {module:qan/api/QANApi~qanGetFilterChangesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetFilterChanges}
     */
    qanGetFilterChanges(filterId, callback) {
      let postBody = null;
      // verify the required parameter 'filterId' is set
      if (filterId === undefined || filterId === null) {
        throw new Error("Missing the required parameter 'filterId' when calling qanGetFilterChanges");
      }

      let pathParams = {
        'FilterId': filterId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetFilterChanges;
      return this.apiClient.callApi(
        '/getFilterChanges/{FilterId}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetFilterLogs operation.
     * @callback module:qan/api/QANApi~qanGetFilterLogsCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetFilterLogs} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an array of all logs matching filter with given id.
     * @param {String} id The filter ID
     * @param {module:qan/api/QANApi~qanGetFilterLogsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetFilterLogs}
     */
    qanGetFilterLogs(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling qanGetFilterLogs");
      }

      let pathParams = {
        'Id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetFilterLogs;
      return this.apiClient.callApi(
        '/getFilterLogs/{Id}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetLogs operation.
     * @callback module:qan/api/QANApi~qanGetLogsCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetLogs} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an array of all logs matching a given filter object.
     * @param {module:qan/qan/InputGetLogs} inputGetLogs 
     * @param {module:qan/api/QANApi~qanGetLogsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetLogs}
     */
    qanGetLogs(inputGetLogs, callback) {
      let postBody = inputGetLogs;
      // verify the required parameter 'inputGetLogs' is set
      if (inputGetLogs === undefined || inputGetLogs === null) {
        throw new Error("Missing the required parameter 'inputGetLogs' when calling qanGetLogs");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetLogs;
      return this.apiClient.callApi(
        '/getLogs/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetProof operation.
     * @callback module:qan/api/QANApi~qanGetProofCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetProof} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the account and storage values of the specified account including the Merkle-proof.
     * @param {module:qan/qan/InputGetProof} inputGetProof 
     * @param {module:qan/api/QANApi~qanGetProofCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetProof}
     */
    qanGetProof(inputGetProof, callback) {
      let postBody = inputGetProof;
      // verify the required parameter 'inputGetProof' is set
      if (inputGetProof === undefined || inputGetProof === null) {
        throw new Error("Missing the required parameter 'inputGetProof' when calling qanGetProof");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetProof;
      return this.apiClient.callApi(
        '/getProof/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetStorageAt operation.
     * @callback module:qan/api/QANApi~qanGetStorageAtCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetStorageAt} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the value from a storage position at a given address.
     * @param {module:qan/qan/InputGetStorageAt} inputGetStorageAt 
     * @param {module:qan/api/QANApi~qanGetStorageAtCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetStorageAt}
     */
    qanGetStorageAt(inputGetStorageAt, callback) {
      let postBody = inputGetStorageAt;
      // verify the required parameter 'inputGetStorageAt' is set
      if (inputGetStorageAt === undefined || inputGetStorageAt === null) {
        throw new Error("Missing the required parameter 'inputGetStorageAt' when calling qanGetStorageAt");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetStorageAt;
      return this.apiClient.callApi(
        '/getStorageAt/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetTransactionByBlockHashAndIndex operation.
     * @callback module:qan/api/QANApi~qanGetTransactionByBlockHashAndIndexCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetTransactionByBlockHashAndIndex} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns information about a transaction given a blockhash and transaction index position.
     * @param {String} blockHash 
     * @param {String} index An integer of the transaction index position
     * @param {module:qan/api/QANApi~qanGetTransactionByBlockHashAndIndexCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetTransactionByBlockHashAndIndex}
     */
    qanGetTransactionByBlockHashAndIndex(blockHash, index, callback) {
      let postBody = null;
      // verify the required parameter 'blockHash' is set
      if (blockHash === undefined || blockHash === null) {
        throw new Error("Missing the required parameter 'blockHash' when calling qanGetTransactionByBlockHashAndIndex");
      }
      // verify the required parameter 'index' is set
      if (index === undefined || index === null) {
        throw new Error("Missing the required parameter 'index' when calling qanGetTransactionByBlockHashAndIndex");
      }

      let pathParams = {
        'blockHash': blockHash,
        'index': index
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetTransactionByBlockHashAndIndex;
      return this.apiClient.callApi(
        '/getTransactionByBlockHashAndIndex/{blockHash}/{index}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetTransactionByBlockNumberAndIndex operation.
     * @callback module:qan/api/QANApi~qanGetTransactionByBlockNumberAndIndexCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetTransactionByBlockNumberAndIndex} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns information about a transaction given a block number and transaction index position.
     * @param {String} blockNumber The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {String} index An integer of the transaction index position
     * @param {module:qan/api/QANApi~qanGetTransactionByBlockNumberAndIndexCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetTransactionByBlockNumberAndIndex}
     */
    qanGetTransactionByBlockNumberAndIndex(blockNumber, index, callback) {
      let postBody = null;
      // verify the required parameter 'blockNumber' is set
      if (blockNumber === undefined || blockNumber === null) {
        throw new Error("Missing the required parameter 'blockNumber' when calling qanGetTransactionByBlockNumberAndIndex");
      }
      // verify the required parameter 'index' is set
      if (index === undefined || index === null) {
        throw new Error("Missing the required parameter 'index' when calling qanGetTransactionByBlockNumberAndIndex");
      }

      let pathParams = {
        'blockNumber': blockNumber,
        'index': index
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetTransactionByBlockNumberAndIndex;
      return this.apiClient.callApi(
        '/getTransactionByBlockNumberAndIndex/{blockNumber}/{index}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetTransactionByHash operation.
     * @callback module:qan/api/QANApi~qanGetTransactionByHashCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetTransactionByHash} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the information about a transaction from a transaction hash.
     * @param {String} hash The hash of a transaction
     * @param {module:qan/api/QANApi~qanGetTransactionByHashCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetTransactionByHash}
     */
    qanGetTransactionByHash(hash, callback) {
      let postBody = null;
      // verify the required parameter 'hash' is set
      if (hash === undefined || hash === null) {
        throw new Error("Missing the required parameter 'hash' when calling qanGetTransactionByHash");
      }

      let pathParams = {
        'hash': hash
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetTransactionByHash;
      return this.apiClient.callApi(
        '/getTransactionByHash/{hash}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetTransactionCount operation.
     * @callback module:qan/api/QANApi~qanGetTransactionCountCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetTransactionCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the number of transactions sent from an address.
     * @param {String} address The address from which the transaction count to be checked
     * @param {String} blockNumber The block number in hexadecimal or decimal format or the string latest, earliest, pending
     * @param {module:qan/api/QANApi~qanGetTransactionCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetTransactionCount}
     */
    qanGetTransactionCount(address, blockNumber, callback) {
      let postBody = null;
      // verify the required parameter 'address' is set
      if (address === undefined || address === null) {
        throw new Error("Missing the required parameter 'address' when calling qanGetTransactionCount");
      }
      // verify the required parameter 'blockNumber' is set
      if (blockNumber === undefined || blockNumber === null) {
        throw new Error("Missing the required parameter 'blockNumber' when calling qanGetTransactionCount");
      }

      let pathParams = {
        'Address': address,
        'BlockNumber': blockNumber
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetTransactionCount;
      return this.apiClient.callApi(
        '/getTransactionCount/{Address}/{BlockNumber}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanGetTransactionReceipt operation.
     * @callback module:qan/api/QANApi~qanGetTransactionReceiptCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputGetTransactionReceipt} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the receipt of a transaction by transaction hash.
     * @param {String} hash The hash of a transaction
     * @param {module:qan/api/QANApi~qanGetTransactionReceiptCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputGetTransactionReceipt}
     */
    qanGetTransactionReceipt(hash, callback) {
      let postBody = null;
      // verify the required parameter 'hash' is set
      if (hash === undefined || hash === null) {
        throw new Error("Missing the required parameter 'hash' when calling qanGetTransactionReceipt");
      }

      let pathParams = {
        'Hash': hash
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputGetTransactionReceipt;
      return this.apiClient.callApi(
        '/getTransactionReceipt/{Hash}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanMaxPriorityFeePerGas operation.
     * @callback module:qan/api/QANApi~qanMaxPriorityFeePerGasCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputMaxPriorityFeePerGas} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the priority fee needed to be included in a block.
     * @param {module:qan/api/QANApi~qanMaxPriorityFeePerGasCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputMaxPriorityFeePerGas}
     */
    qanMaxPriorityFeePerGas(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputMaxPriorityFeePerGas;
      return this.apiClient.callApi(
        '/maxPriorityFeePerGas/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanNewBlockFilter operation.
     * @callback module:qan/api/QANApi~qanNewBlockFilterCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputNewBlockFilter} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a filter in the node, to notify when a new block arrives.
     * @param {module:qan/api/QANApi~qanNewBlockFilterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputNewBlockFilter}
     */
    qanNewBlockFilter(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputNewBlockFilter;
      return this.apiClient.callApi(
        '/newBlockFilter/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanNewFilter operation.
     * @callback module:qan/api/QANApi~qanNewFilterCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputNewFilter} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a filter object, based on filter options, to notify when the state changes (logs).
     * @param {module:qan/qan/InputNewFilter} inputNewFilter 
     * @param {module:qan/api/QANApi~qanNewFilterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputNewFilter}
     */
    qanNewFilter(inputNewFilter, callback) {
      let postBody = inputNewFilter;
      // verify the required parameter 'inputNewFilter' is set
      if (inputNewFilter === undefined || inputNewFilter === null) {
        throw new Error("Missing the required parameter 'inputNewFilter' when calling qanNewFilter");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputNewFilter;
      return this.apiClient.callApi(
        '/newFilter/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanNewPendingTransactionFilter operation.
     * @callback module:qan/api/QANApi~qanNewPendingTransactionFilterCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputNewPendingTransactionFilter} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a filter in the node to notify when new pending transactions arrive.
     * @param {module:qan/api/QANApi~qanNewPendingTransactionFilterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputNewPendingTransactionFilter}
     */
    qanNewPendingTransactionFilter(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputNewPendingTransactionFilter;
      return this.apiClient.callApi(
        '/newPendingTransactionFilter/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanSendRawTransaction operation.
     * @callback module:qan/api/QANApi~qanSendRawTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputSendRawTransaction} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates new message call transaction or a contract creation for signed transactions.
     * @param {module:qan/qan/InputSendRawTransaction} inputSendRawTransaction 
     * @param {module:qan/api/QANApi~qanSendRawTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputSendRawTransaction}
     */
    qanSendRawTransaction(inputSendRawTransaction, callback) {
      let postBody = inputSendRawTransaction;
      // verify the required parameter 'inputSendRawTransaction' is set
      if (inputSendRawTransaction === undefined || inputSendRawTransaction === null) {
        throw new Error("Missing the required parameter 'inputSendRawTransaction' when calling qanSendRawTransaction");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputSendRawTransaction;
      return this.apiClient.callApi(
        '/sendRawTransaction/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanSyncing operation.
     * @callback module:qan/api/QANApi~qanSyncingCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputSyncing} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns an object with the sync status of the node if the node is out-of-sync and is syncing. Returns null when the node is already in sync.
     * @param {module:qan/api/QANApi~qanSyncingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputSyncing}
     */
    qanSyncing(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputSyncing;
      return this.apiClient.callApi(
        '/syncing/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanUninstallFilter operation.
     * @callback module:qan/api/QANApi~qanUninstallFilterCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputUninstallFilter} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Uninstalls a filter with the given filter id.
     * @param {String} filterId The filter ID that needs to be uninstalled. It should always be called when watch is no longer needed. Additionally, Filters timeout when they aren't requested with getFilterChanges for a period of time
     * @param {module:qan/api/QANApi~qanUninstallFilterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputUninstallFilter}
     */
    qanUninstallFilter(filterId, callback) {
      let postBody = null;
      // verify the required parameter 'filterId' is set
      if (filterId === undefined || filterId === null) {
        throw new Error("Missing the required parameter 'filterId' when calling qanUninstallFilter");
      }

      let pathParams = {
        'FilterId': filterId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputUninstallFilter;
      return this.apiClient.callApi(
        '/uninstallFilter/{FilterId}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the qanXlinkValid operation.
     * @callback module:qan/api/QANApi~qanXlinkValidCallback
     * @param {String} error Error message, if any.
     * @param {module:qan/qan/OutputXlinkValid} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns the xlink validity time of the account of given address.
     * @param {String} address 
     * @param {module:qan/api/QANApi~qanXlinkValidCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:qan/qan/OutputXlinkValid}
     */
    qanXlinkValid(address, callback) {
      let postBody = null;
      // verify the required parameter 'address' is set
      if (address === undefined || address === null) {
        throw new Error("Missing the required parameter 'address' when calling qanXlinkValid");
      }

      let pathParams = {
        'Address': address
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json', 'application/problem+json'];
      let returnType = OutputXlinkValid;
      return this.apiClient.callApi(
        '/xlinkValid/{Address}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
