/**
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ErrorDetail from './qan/ErrorDetail';
import ErrorModel from './qan/ErrorModel';
import EstimateGasObject from './qan/EstimateGasObject';
import FilterObject from './qan/FilterObject';
import InputCall from './qan/InputCall';
import InputEstimateGas from './qan/InputEstimateGas';
import InputFeeHistory from './qan/InputFeeHistory';
import InputGetLogs from './qan/InputGetLogs';
import InputGetProof from './qan/InputGetProof';
import InputGetStorageAt from './qan/InputGetStorageAt';
import InputNewFilter from './qan/InputNewFilter';
import InputSendRawTransaction from './qan/InputSendRawTransaction';
import OutputBlockNumber from './qan/OutputBlockNumber';
import OutputCall from './qan/OutputCall';
import OutputChainId from './qan/OutputChainId';
import OutputEstimateGas from './qan/OutputEstimateGas';
import OutputFeeHistory from './qan/OutputFeeHistory';
import OutputGasPrice from './qan/OutputGasPrice';
import OutputGetBalance from './qan/OutputGetBalance';
import OutputGetBlockByHash from './qan/OutputGetBlockByHash';
import OutputGetBlockByNumber from './qan/OutputGetBlockByNumber';
import OutputGetBlockReceipts from './qan/OutputGetBlockReceipts';
import OutputGetBlockTransactionCountByHash from './qan/OutputGetBlockTransactionCountByHash';
import OutputGetBlockTransactionCountByNumber from './qan/OutputGetBlockTransactionCountByNumber';
import OutputGetCode from './qan/OutputGetCode';
import OutputGetFilterChanges from './qan/OutputGetFilterChanges';
import OutputGetFilterLogs from './qan/OutputGetFilterLogs';
import OutputGetLogs from './qan/OutputGetLogs';
import OutputGetProof from './qan/OutputGetProof';
import OutputGetStorageAt from './qan/OutputGetStorageAt';
import OutputGetTransactionByBlockHashAndIndex from './qan/OutputGetTransactionByBlockHashAndIndex';
import OutputGetTransactionByBlockNumberAndIndex from './qan/OutputGetTransactionByBlockNumberAndIndex';
import OutputGetTransactionByHash from './qan/OutputGetTransactionByHash';
import OutputGetTransactionCount from './qan/OutputGetTransactionCount';
import OutputGetTransactionReceipt from './qan/OutputGetTransactionReceipt';
import OutputMaxPriorityFeePerGas from './qan/OutputMaxPriorityFeePerGas';
import OutputNewBlockFilter from './qan/OutputNewBlockFilter';
import OutputNewFilter from './qan/OutputNewFilter';
import OutputNewPendingTransactionFilter from './qan/OutputNewPendingTransactionFilter';
import OutputSendRawTransaction from './qan/OutputSendRawTransaction';
import OutputSyncing from './qan/OutputSyncing';
import OutputUninstallFilter from './qan/OutputUninstallFilter';
import OutputXlinkValid from './qan/OutputXlinkValid';
import ParamsTransaction from './qan/ParamsTransaction';
import ResponseBlock from './qan/ResponseBlock';
import ResponseLog from './qan/ResponseLog';
import ResponseStorageEntry from './qan/ResponseStorageEntry';
import ResponseTransaction from './qan/ResponseTransaction';
import ResponseTransactionReceipt from './qan/ResponseTransactionReceipt';
import ResponseWithdrawals from './qan/ResponseWithdrawals';
import SyncStatus from './qan/SyncStatus';
import QANApi from './api/QANApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var QanAutoApi = require('qan/index'); // See note below*.
* var xxxSvc = new QanAutoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new QanAutoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['qan/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new QanAutoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new QanAutoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module qan/index
* @version 0.0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:qan/ApiClient}
     */
    ApiClient,

    /**
     * The ErrorDetail model constructor.
     * @property {module:qan/qan/ErrorDetail}
     */
    ErrorDetail,

    /**
     * The ErrorModel model constructor.
     * @property {module:qan/qan/ErrorModel}
     */
    ErrorModel,

    /**
     * The EstimateGasObject model constructor.
     * @property {module:qan/qan/EstimateGasObject}
     */
    EstimateGasObject,

    /**
     * The FilterObject model constructor.
     * @property {module:qan/qan/FilterObject}
     */
    FilterObject,

    /**
     * The InputCall model constructor.
     * @property {module:qan/qan/InputCall}
     */
    InputCall,

    /**
     * The InputEstimateGas model constructor.
     * @property {module:qan/qan/InputEstimateGas}
     */
    InputEstimateGas,

    /**
     * The InputFeeHistory model constructor.
     * @property {module:qan/qan/InputFeeHistory}
     */
    InputFeeHistory,

    /**
     * The InputGetLogs model constructor.
     * @property {module:qan/qan/InputGetLogs}
     */
    InputGetLogs,

    /**
     * The InputGetProof model constructor.
     * @property {module:qan/qan/InputGetProof}
     */
    InputGetProof,

    /**
     * The InputGetStorageAt model constructor.
     * @property {module:qan/qan/InputGetStorageAt}
     */
    InputGetStorageAt,

    /**
     * The InputNewFilter model constructor.
     * @property {module:qan/qan/InputNewFilter}
     */
    InputNewFilter,

    /**
     * The InputSendRawTransaction model constructor.
     * @property {module:qan/qan/InputSendRawTransaction}
     */
    InputSendRawTransaction,

    /**
     * The OutputBlockNumber model constructor.
     * @property {module:qan/qan/OutputBlockNumber}
     */
    OutputBlockNumber,

    /**
     * The OutputCall model constructor.
     * @property {module:qan/qan/OutputCall}
     */
    OutputCall,

    /**
     * The OutputChainId model constructor.
     * @property {module:qan/qan/OutputChainId}
     */
    OutputChainId,

    /**
     * The OutputEstimateGas model constructor.
     * @property {module:qan/qan/OutputEstimateGas}
     */
    OutputEstimateGas,

    /**
     * The OutputFeeHistory model constructor.
     * @property {module:qan/qan/OutputFeeHistory}
     */
    OutputFeeHistory,

    /**
     * The OutputGasPrice model constructor.
     * @property {module:qan/qan/OutputGasPrice}
     */
    OutputGasPrice,

    /**
     * The OutputGetBalance model constructor.
     * @property {module:qan/qan/OutputGetBalance}
     */
    OutputGetBalance,

    /**
     * The OutputGetBlockByHash model constructor.
     * @property {module:qan/qan/OutputGetBlockByHash}
     */
    OutputGetBlockByHash,

    /**
     * The OutputGetBlockByNumber model constructor.
     * @property {module:qan/qan/OutputGetBlockByNumber}
     */
    OutputGetBlockByNumber,

    /**
     * The OutputGetBlockReceipts model constructor.
     * @property {module:qan/qan/OutputGetBlockReceipts}
     */
    OutputGetBlockReceipts,

    /**
     * The OutputGetBlockTransactionCountByHash model constructor.
     * @property {module:qan/qan/OutputGetBlockTransactionCountByHash}
     */
    OutputGetBlockTransactionCountByHash,

    /**
     * The OutputGetBlockTransactionCountByNumber model constructor.
     * @property {module:qan/qan/OutputGetBlockTransactionCountByNumber}
     */
    OutputGetBlockTransactionCountByNumber,

    /**
     * The OutputGetCode model constructor.
     * @property {module:qan/qan/OutputGetCode}
     */
    OutputGetCode,

    /**
     * The OutputGetFilterChanges model constructor.
     * @property {module:qan/qan/OutputGetFilterChanges}
     */
    OutputGetFilterChanges,

    /**
     * The OutputGetFilterLogs model constructor.
     * @property {module:qan/qan/OutputGetFilterLogs}
     */
    OutputGetFilterLogs,

    /**
     * The OutputGetLogs model constructor.
     * @property {module:qan/qan/OutputGetLogs}
     */
    OutputGetLogs,

    /**
     * The OutputGetProof model constructor.
     * @property {module:qan/qan/OutputGetProof}
     */
    OutputGetProof,

    /**
     * The OutputGetStorageAt model constructor.
     * @property {module:qan/qan/OutputGetStorageAt}
     */
    OutputGetStorageAt,

    /**
     * The OutputGetTransactionByBlockHashAndIndex model constructor.
     * @property {module:qan/qan/OutputGetTransactionByBlockHashAndIndex}
     */
    OutputGetTransactionByBlockHashAndIndex,

    /**
     * The OutputGetTransactionByBlockNumberAndIndex model constructor.
     * @property {module:qan/qan/OutputGetTransactionByBlockNumberAndIndex}
     */
    OutputGetTransactionByBlockNumberAndIndex,

    /**
     * The OutputGetTransactionByHash model constructor.
     * @property {module:qan/qan/OutputGetTransactionByHash}
     */
    OutputGetTransactionByHash,

    /**
     * The OutputGetTransactionCount model constructor.
     * @property {module:qan/qan/OutputGetTransactionCount}
     */
    OutputGetTransactionCount,

    /**
     * The OutputGetTransactionReceipt model constructor.
     * @property {module:qan/qan/OutputGetTransactionReceipt}
     */
    OutputGetTransactionReceipt,

    /**
     * The OutputMaxPriorityFeePerGas model constructor.
     * @property {module:qan/qan/OutputMaxPriorityFeePerGas}
     */
    OutputMaxPriorityFeePerGas,

    /**
     * The OutputNewBlockFilter model constructor.
     * @property {module:qan/qan/OutputNewBlockFilter}
     */
    OutputNewBlockFilter,

    /**
     * The OutputNewFilter model constructor.
     * @property {module:qan/qan/OutputNewFilter}
     */
    OutputNewFilter,

    /**
     * The OutputNewPendingTransactionFilter model constructor.
     * @property {module:qan/qan/OutputNewPendingTransactionFilter}
     */
    OutputNewPendingTransactionFilter,

    /**
     * The OutputSendRawTransaction model constructor.
     * @property {module:qan/qan/OutputSendRawTransaction}
     */
    OutputSendRawTransaction,

    /**
     * The OutputSyncing model constructor.
     * @property {module:qan/qan/OutputSyncing}
     */
    OutputSyncing,

    /**
     * The OutputUninstallFilter model constructor.
     * @property {module:qan/qan/OutputUninstallFilter}
     */
    OutputUninstallFilter,

    /**
     * The OutputXlinkValid model constructor.
     * @property {module:qan/qan/OutputXlinkValid}
     */
    OutputXlinkValid,

    /**
     * The ParamsTransaction model constructor.
     * @property {module:qan/qan/ParamsTransaction}
     */
    ParamsTransaction,

    /**
     * The ResponseBlock model constructor.
     * @property {module:qan/qan/ResponseBlock}
     */
    ResponseBlock,

    /**
     * The ResponseLog model constructor.
     * @property {module:qan/qan/ResponseLog}
     */
    ResponseLog,

    /**
     * The ResponseStorageEntry model constructor.
     * @property {module:qan/qan/ResponseStorageEntry}
     */
    ResponseStorageEntry,

    /**
     * The ResponseTransaction model constructor.
     * @property {module:qan/qan/ResponseTransaction}
     */
    ResponseTransaction,

    /**
     * The ResponseTransactionReceipt model constructor.
     * @property {module:qan/qan/ResponseTransactionReceipt}
     */
    ResponseTransactionReceipt,

    /**
     * The ResponseWithdrawals model constructor.
     * @property {module:qan/qan/ResponseWithdrawals}
     */
    ResponseWithdrawals,

    /**
     * The SyncStatus model constructor.
     * @property {module:qan/qan/SyncStatus}
     */
    SyncStatus,

    /**
    * The QANApi service constructor.
    * @property {module:qan/api/QANApi}
    */
    QANApi
};
